CREATE TABLE transactions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    transaction_id  VARCHAR(255)                            NOT NULL,
    idempotency_key VARCHAR(255)                            NOT NULL,
    customer_id     VARCHAR(255),
    amount          DECIMAL,
    currency        VARCHAR(255),
    country         VARCHAR(255),
    device_id       VARCHAR(255),
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE transactions
    ADD CONSTRAINT uk_idempotency_key UNIQUE (idempotency_key);

ALTER TABLE transactions
    ADD CONSTRAINT uk_transaction_id UNIQUE (transaction_id);