spring.application.name=fraud_action_service
server.port=8004

# ===============================
# Kafka
# ===============================
sping.kafka.bootstrap-servers=

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.com.example.action_service_fraud_detection=DEBUG

# Include Correlation ID in logs
logging.pattern.level=%5p [X-Correlation-Id=%X{X-Correlation-Id}]