spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO}
          default-label: main

server:
  port: 8888

#https://github.com/FearLessXT/fraud_detection_config_repo
