spring.application.name=decision_service_fraud
server.port=9005

# ===========================
# kafka
# ===========================
spring.kafka.bootstrap-servers=localhost:9092

# ===========================
# kafka
# ===========================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.com.example.decision_service_fraud=DEBUG

#include correlation ID in logs
logging.pattern.level=%5p [X-Correlation-Id=%X{X-Correlation-Id}]