spring.application.name=auth_service_fraud
server.port=8001

# ===============================
# Datasource
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/fraud_detection?autoReconnect=true
spring.datasource.username=postgres
spring.datasource.password=root

# ===============================
# OAuth2 Authorization Server
# ===============================
spring.security.oauth2.authorizationserver.issuer=http://localhost:8001

# ===============================
# Fraud Client Configuration
# ===============================
fraud.oauth.client-id=fraud-client
fraud.oauth.client-secret=fraud-secret

# ===============================
# Logging (useful during dev)
# ===============================
logging.level.org.springframework.security=DEBUG